/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.main.auth.login": [],
    "filament.main.auth.logout": [],
    "filament.main.pages.dashboard": [],
    "filament.main.pages.about-us": [],
    "filament.main.pages.profile": [],
    "filament.main.pages.setting-website": [],
    "filament.main.resources.categories.index": [],
    "filament.main.resources.contactuses.index": [],
    "filament.main.resources.contactuses.create": [],
    "filament.main.resources.contactuses.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.main.resources.faqs.index": [],
    "filament.main.resources.faqs.create": [],
    "filament.main.resources.faqs.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.main.resources.kelas.index": [],
    "filament.main.resources.kelas.create": [],
    "filament.main.resources.kelas.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.main.resources.kelas.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.main.resources.levels.index": [],
    "filament.main.resources.mentors.index": [],
    "filament.main.resources.mentors.create": [],
    "filament.main.resources.mentors.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.main.resources.news-categories.index": [],
    "filament.main.resources.news.index": [],
    "filament.main.resources.news.create": [],
    "filament.main.resources.news.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.main.resources.sections.index": [],
    "filament.main.resources.sections.create": [],
    "filament.main.resources.sections.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.main.resources.students.index": [],
    "filament.main.resources.students.create": [],
    "filament.main.resources.students.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.main.resources.transaksis.index": [],
    "filament.main.resources.transaksis.create": [],
    "filament.main.resources.transaksis.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.main.resources.types.index": [],
    "filament.main.resources.users.index": [],
    "filament.main.resources.users.create": [],
    "filament.main.resources.users.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.mentor.auth.login": [],
    "filament.mentor.auth.logout": [],
    "filament.mentor.pages.dashboard": [],
    "filament.mentor.pages.profile": [],
    "filament.mentor.resources.kelas.index": [],
    "filament.mentor.resources.kelas.create": [],
    "filament.mentor.resources.kelas.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.mentor.resources.sections.index": [],
    "filament.mentor.resources.sections.create": [],
    "filament.mentor.resources.sections.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.mentor.resources.types.index": [],
    "filament.mentor.resources.types.create": [],
    "filament.mentor.resources.types.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "sanctum.csrf-cookie": [],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "home": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
